server: 
  port: 9999
mybatis: # mybatis配置官方说明 http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
spring: 
  application: 
    name: uid-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.0.16.135:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: shinow666
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
logging: 
  file: ../logs/uid-consumer.log
  level: 
    io.prong.uid: ERROR
    root: INFO
# 以下为可选配置, 如未指定将采用默认值
prong: 
  uid: 
    timeBits: 29
    workerBits: 21
    seqBits: 13
    epochStr: "2018-11-26"
    CachedUidGenerator:
      boost-power: 3          # RingBuffer size扩容参数, 可提高UID生成的吞吐量, 默认:3
      padding-factor: 50      # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
      #schedule-interval: 60  # 默认:不配置此项, 即不实用Schedule线程. 如需使用, 请指定Schedule线程时间间隔, 单位:秒
 
