server:
  port: 8080
  servlet:
    context-path: /m8ts-plus
  tomcat:
    uri-encoding: UTF-8

spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.0.16.135:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: shinow666
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10

mybatis-plus:
  mapper-locations: mapper/**/*.xml,classpath*:mapper/**/*.xml
  type-aliases-package: com.yourmp.entity
  global-config:
    refresh: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

prong:
  uid:
    timeBits: 29
    workerBits: 21
    seqBits: 13
    epochStr: "2018-12-18"
    CachedUidGenerator:
      boost-power: 3
      padding-factor: 50

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper